development:
  adapter: sqlite3
  encoding: unicode
  database: db_development
  pool: 5
  username: 
  password:

test:
  adapter: sqlite3
  encoding: unicode
  database: db_test
  pool: 5
  username: 
  password:
  test:
